/**:
    ros__parameters:

        # Mask Parameters
        width_tolerance: 275
        height_scale: 0.25

        # Hough Transform Parameters
        rho: 1
        threshold: 45
        min_line_length: 25
        max_line_gap: 15

        # Waypoint Parameters
        look_dist: 300


